---
default_language_version:
    python: python3.10
# hooks
repos:
    - repo: local
      hooks:
          - id: eslint
            name: eslint
            language: system
            exclude: ^services/
            entry: npx lint-staged
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: no-commit-to-branch
            args: [--branch, main]
          - id: check-toml
          - id: end-of-file-fixer
          - id: trailing-whitespace
    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.28.0
      hooks:
          - id: yamllint
            args: [-d relaxed]
    - repo: https://github.com/pycqa/isort
      rev: 5.6.4
      hooks:
          - id: isort
            args: [--profile=black, --filter-files]  # https://pycqa.github.io/isort/docs/configuration/black_compatibility.html
    - repo: https://github.com/psf/black
      rev: 22.10.0
      hooks:
          - id: black
            exclude: ^frontend/
            args: [./services, --line-length=88]
    - repo: https://github.com/PyCQA/flake8
      rev: 5.0.4
      hooks:
          - id: flake8
            args: [--max-line-length=88, --extend-ignore=E203]  # https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html
