[tool.poetry]
name = "utilities"
version = "0.1.0"
description = "Shared utilities"
authors = [
    "Fahad Awan",
    "Donato Quartuccia",
    "Ethan Rietz",
]

[tool.poetry.dependencies]
python = "^3.10"
librosa = "^0.9.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
