[tool.poetry]
name = "neural-network"
version = "0.1.0"
description = ""
authors = [
    "Fahad Awan <awan.fahad@gmail.com>",
    "Donato Quartuccia <66536458+donatosaur@users.noreply.github.com>",
    "Ethan Rietz <ewrietz@gmail.com>",
]
readme = "README.md"
packages = [{include = "neural_network"}]

[tool.poetry.dependencies]
python = "^3.10"
utilities = {path = "../utilities"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
